# Generated by Django 5.2.13 on 2026-05-04 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_months',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='External image URL for catalog cards'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CoursePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='courses.course')),
            ],
            options={
                'ordering': ('course', 'phase_number'),
                'unique_together': {('course', 'phase_number')},
            },
        ),
        migrations.CreateModel(
            name='CoursePhaseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(default=list, help_text='List of 30: {question, options[4], answer_index}')),
                ('pass_mark_percent', models.PositiveSmallIntegerField(default=60)),
                ('phase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.coursephase')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePhaseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('quiz_score_percent', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.coursephase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'phase')},
            },
        ),
    ]
