# Generated by Django 5.2.13 on 2026-05-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_duration_months_course_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursephase',
            name='resources',
            field=models.JSONField(default=list, help_text='List of reading resources: [{title, url}]'),
        ),
        migrations.AddField(
            model_name='coursephaseprogress',
            name='reading_completed',
            field=models.BooleanField(default=False),
        ),
    ]
