# Generated by Django 5.2.13 on 2026-05-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursephase_resources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.JSONField(default=list, help_text="What you'll learn bullet points"),
        ),
        migrations.AddField(
            model_name='course',
            name='related_topics',
            field=models.JSONField(default=list, help_text='Related topic chips'),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.JSONField(default=list, help_text='Course requirements list'),
        ),
    ]
